### PR TITLE
Add: ITA-Frecciabianca

### PR DESCRIPTION
**Pull request by eeffaann**

### CODE REVIEW

**Comment by michihdeu** [comment]
@eeffaann what about `Rome - Ravenna`?
https://en.wikipedia.org/wiki/Frecciabianca

**Comment by eeffaann** [comment]
> @eeffaann what about `Rome - Ravenna`? https://en.wikipedia.org/wiki/Frecciabianca

Upgraded to Frecciargento this year. Italian Wikipedia has been updated: https://it.wikipedia.org/wiki/Frecciabianca#Tratte

**Comment by jteresco** [comment]
I'll wait to merge this in until I get confirmation it's ready to go.

**Comment by michihdeu** [comment]
My question is answered. Fine. I just wonder how many tiny systems we will have in the end. Talking about Italy. Talking in general. @si404 thoughts? Or ready to go?

**Comment by michihdeu** [comment]
I appreciate adding Italian systems though. Just traveled by train on Sardinia last week. Would love to see the route in RB.

**Comment by si404** [comment]
The discussion about system merging is one for the forum.

This system is fine (and even if it was incomplete, that's not a reason to stop a pull).

**Comment by michihdeu** [comment]
https://forum.travelmapping.net/index.php?topic=6495

**Pull request merged**
