### PR TITLE
First six Japan systems

### PR DESCRIPTION
**Pull request by denishanson**
Shikoku systems plus all-Japan monorails

### CODE REVIEW

**Comment by denishanson** [comment]
Did NOT run datacheck because I do not know how to do so for railway data.

**Comment by jteresco** [comment]
Fixes needed:

<pre>
[3.3] ABORTING due to 27 errors:
1: Could not parse jpshiyo_con.csv line: [jpshiyo;IyoGunLn;;;Gunchu Line;jpniyo.gunchu], expected 5 fields, found 6
2: Could not parse jpshiyo_con.csv line: [jpshiyo;IyoTakaLn;;;Takahama Line;jpniyo.takahama], expected 5 fields, found 6
3: Could not parse jpshiyo_con.csv line: [jpshiyo;IyoYokoLn;;;Yokogawara Line;jpniyo.yokogawara], expected 5 fields, found 6
4: Could not parse jpshkot_con.csv line: [jpshkot;KotKotLn;;;Kotohira Line;jpnkot.kotohira], expected 5 fields, found 6
5: Could not parse jpshkot_con.csv line: [jpshkot;KotNagLn;;;Nagao Line;jpnkot.nagao], expected 5 fields, found 6
6: Could not parse jpshkot_con.csv line: [jpshkot;KotShiLn;;;Shido Line;jpnkot.shido], expected 5 fields, found 6
7: Could not parse jpshtos_con.csv line: [jpshtos;TosGomLn;;;Gomen-Nahari Line;jpntos.gomen], expected 5 fields, found 6
8: Could not parse jpshtos_con.csv line: [jpshtos;TosNakLn;;;Nakamura-Sukumo Line;jpntos.nakasuku], expected 5 fields, found 6
9: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/RailwayData/data/JPN/jpmono/jpmno.chiba1.wpt'
10: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/RailwayData/data/JPN/jpmono/jpmno.chiba2.wpt'
11: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/RailwayData/data/JPN/jpmono/jpmno.disney.wpt'
12: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/RailwayData/data/JPN/jpmono/jpmno.kitakyushu.wpt'
13: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/RailwayData/data/JPN/jpmono/jpmno.okinawa.wpt'
14: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/RailwayData/data/JPN/jpmono/jpmno.osakamain.wpt'
15: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/RailwayData/data/JPN/jpmono/jpmno.osakasaito.wpt'
16: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/RailwayData/data/JPN/jpmono/jpmno.shonan.wpt'
17: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/RailwayData/data/JPN/jpmono/jpmno.skyrail.wpt'
18: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/RailwayData/data/JPN/jpmono/jpmno.tamatoshi.wpt'
19: [Errno 2] No such file or directory: '/fast/home/terescoj/travelmapping/RailwayData/data/JPN/jpmono/jpmno.tokyo.wpt'
20: jpshiyo.csv: root jpniyo.gunchu not matched by any connected route root.
21: jpshiyo.csv: root jpniyo.takahama not matched by any connected route root.
22: jpshiyo.csv: root jpniyo.yokogawara not matched by any connected route root.
23: jpshkot.csv: root jpnkot.kotohira not matched by any connected route root.
24: jpshkot.csv: root jpnkot.nagao not matched by any connected route root.
25: jpshkot.csv: root jpnkot.shido not matched by any connected route root.
26: jpshtos.csv: root jpntos.gomen not matched by any connected route root.
27: jpshtos.csv: root jpntos.nakasuku not matched by any connected route root.
</pre>

**Comment by michihdeu** [comment]
> Did NOT run datacheck because I do not know how to do so for railway data.

/fast/tm/datacheck --rail

**Comment by denishanson** [comment]
Thanks for the command.  Datacheck fails because kokudou doesn't have a
RailwayData directory. How do I get the Railway data directory added to
kokudou?

**Comment by si404** [comment]
> Thanks for the command.  Datacheck fails because kokudou doesn't have a
RailwayData directory. How do I get the Railway data directory added to
kokudou?

That's not the problem - the issue is the file names (which don't conform to site standards anyway, but that's a different problem from it not working)

Going through the errors:
1-8) You need to remove a semicolon in those _con.csv files - instead of ';;;' it needs to be ';;'
9-19) The files that aren't found are 'jp**n**mono.route.wpt', but are listed in the csv as 'jpmono.route.wpt'
20-27) Errors created by errors 1-8

**Comment by jteresco** [comment]
To get a clone of the `RailwayData` repository, you'll need to do:

git clone https://github.com/denishanson/RailwayData.git

**Comment by jteresco** [comment]
Site update successful after fixes in #83

**Comment by denishanson** [comment]
I will change jpnxxx to jpn. I was using the xxx suffix to differentiate
between route names because there are duplicate names across systems.

Should I make the xxx a prefix to the route name?  Is there an accepted way
for handling a case like this?
    jpnama.amagi.wpt  --> jpn.amaamagi.wpt
    jpnnnr.amagi.wpt  -->  jpn.nnramagi.wpt

Thanks, Denis

**Pull request merged**
