### PR TITLE
Add ESP-AVE

### PR DESCRIPTION
**Pull request by eeffaann**

### CODE REVIEW

**Comment by eeffaann** [comment]
!!! DATA CHECK SUCCESSFUL !!!

**Comment by jteresco** [comment]
We have a bad line 33 in espct.madbarfig.wpt.  Site update failed.  @eeffaann @si404

**Comment by eeffaann** [comment]
Looks like a fat fingered node name, I can fix in an hour or so, though might be worth looking at how it passed Data Check?

**Comment by michihdeu** [comment]
> Looks like a fat fingered node name, I can fix in an hour or so, though might be worth looking at how it passed Data Check?

@yakra ?

**Comment by yakra** [comment]
Sorry, just now noticed I was pinged here.
It makes sense to me how this is a "legit" label from a siteupdate standpoint.
This would generate SQL like
```sql
INSERT INTO waypoints VALUES
('100001','AR/CT','41.615635','0.347443','espct.madbarfig')
...
,('100033','\','41.354514','1.192096','espct.madbarfig')
```
@jteresco, what happened when you tried to ingest the .sql file?
My first guess is...
* The backslash escapes the next single quote, making the label string `',`
* The single quote *after that* closes the label string rather than open the latitude string.
* This might be the case if GitHub's syntax highlighting is an indication. Note the lighter blue.
* Once we have extra unquoted text after *that*, we have problems. A malformed SQL command.
* site update process go boom

---

The thing to do is probably put some additional checks into `Waypoint::label_invalid_char()` to make certain bad characters a fatal `ErrorList` error.
I've thought for a while that function needs a rewrite. A sensible binary search, some readable character literals, maybe a lambda... Now I have an excuse...

**Comment by jteresco** [comment]
@yakra I believe your first guess is exactly what happened.

**Pull request merged**
