### PR TITLE
LUX/NI

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by jteresco** [comment]
This caused a failure on DB import:

`ERROR 1406 (22001) at line 598120: Data too long for column 'label1' at row 12250`

One of the labels being added to the `datacheckErrors` table is too long for the DB.

@michihdeu

**Comment by michihdeu** [comment]
@jteresco data check was successful! What label is too long? The longest wp label is not new, I’ve only moved it from one route to another….. No detailed output @yakra ?

**Comment by michihdeu** [comment]
I run data check again. Successful….. what can I do?

**Comment by yakra** [comment]
I was just about to post in the forum that the rail update's been hung for a few hours, then checked in here....
It sounds like a problem with the datacheckErrors table.
A little shell scripting and I should be able to zero in on the error.

**Comment by yakra** [comment]
My bad! A bug was introduced in in #641.
LOL, I guess that validate_label.cpp got a little too crazy.

```sh
fgrep -rn -f <(for l in $(tail -n +5 datacheck.log | cut -f2 -d';'); do if [ $(echo $l | wc -c) -gt 26 ]; then echo $l; fi; done | sort | uniq) /fast/home/terescoj/travelmapping/RailwayData/data | sed 's~/fast/home/terescoj/travelmapping/RailwayData/data/~~'
NY/usalirr/ny.hembra.wpt:17:*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666
NY/usalirr/ny.monbra.wpt:17:*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666
NY/usalirr/ny.oysbaybra.wpt:6:*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666
NY/usalirr/ny.portjefbra.wpt:17:*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666
NY/usalirr/ny.ronbra.wpt:17:*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666
NY/usalirr/ny.ronbragct.wpt:17:*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666
```
A `+` before a `*` in a label is allowed (even if it's unnecessary as the label is hidden and the `*` is ignored in .lists).
A `*` before a `+`, however, is not, so the datacheck was designed to flag that.
But I pooched it. The "label" flagged is not just the offending label, but the entire rest of the .wpt line:
```sh
[yakra@noreaster /fast/home/terescoj/travelmapping/DataProcessing/siteupdate/2024-09-30@21:38:27/rlogs]$ fgrep 'http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666' datacheck.log
ny.hembra;*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666;;;LABEL_INVALID_CHAR;
ny.monbra;*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666;;;LABEL_INVALID_CHAR;
ny.oysbaybra;*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666;;;LABEL_INVALID_CHAR;
ny.portjefbra;*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666;;;LABEL_INVALID_CHAR;
ny.ronbra;*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666;;;LABEL_INVALID_CHAR;
ny.ronbragct;*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666;;;LABEL_INVALID_CHAR;
```

Cutting the label down to just the necessary substring is easy enough, although another thing I overlooked is that we can't just plop into a datacheck entry (and thus the DB) without first verifying there are no control chars, backslashes, quotation marks, or anything that'd mess up the DB. But no problem, [move the bool earlier, un-lambda the inner lambda, send the pointer on thru the rest of the outer lambda, make good](https://www.youtube.com/watch?v=v3Q2HZRjHHQ&t=85s). LOL, already up way too late tonight but now that I've figured it out implementation should be easy.

**Comment by yakra** [comment]
**Nope,** nothing here is your fault.

This is an issue *now* and not [earlier](https://github.com/TravelMapping/DataProcessing/pull/641#ref-commit-a31f435) (these points are more than a year old) because Jim had still been using an old commit (37c5ee3, the parent commit of my robustness improvement that broke robustness) until last night.

**Comment by yakra** [comment]
Moral of the story:
When I make changes to the code gotta be sure to test them with both Hwy & Rail data now.
*Have* tarted doing that though. :)

**Comment by jteresco** [comment]
I forgot that I had updated to a new siteupdate version since the last rail update.  It was a few days between any user or rail line data updates.

**Comment by michihdeu** [comment]
But why did my data check not have the issue? Don‘t you update it simultaniuosly? @jteresco

**Comment by jteresco** [comment]
I did update to the same version, but this error didn't show up until it tried to populate the database.  And we don't do that step on datacheck runs.

**Comment by jteresco** [comment]
Looks like we have success with @yakra's updated code.

**Comment by michihdeu** [comment]
> I did update to the same version, but this error didn't show up until it tried to populate the database. And we don't do that step on datacheck runs.

that‘s not good. Data check should output all errors IMO.

**Comment by yakra** [comment]
The error was not in the **HighwayData**, but on the **DataProcessing** side, in my datacheck implementation.

The error in the data wasn't *in itself* something that would break the DB; it just had to go into the `datacheckErrors` table and datacheck.log, and life goes on. Same as with other normal datacheck errors.

That is, under normal circumstances -- *if I had coded it right!* :rofl:

`*+DIV_BelPk` was all that was supposed to go into the DB field.
\`Cuz I messed up, it siteupdate tried to put `*+DIV_BelPk http://www.openstreetmap.org/?lat=40.719087&lon=-73.729666` in there instead, treating the URL as if it was also part of the *label*. Which ended up being too long, and  made stuff blow up.

If everything's working right, this won't happen. But this bug's been fixed, at least.

**Pull request merged**
