### PR TITLE
Remove all update entries

### PR DESCRIPTION
**Pull request by michihdeu**
@jteresco be careful though!

### CODE REVIEW

**Comment by michihdeu** [comment]
@si404 there is no need for a dummy entry anymore. @yakra has fixed it!

**Comment by michihdeu** [comment]
https://github.com/TravelMapping/DataProcessing/issues/596
https://github.com/TravelMapping/DataProcessing/pull/658

**Comment by si404** [comment]
So the minor reason has gone. Doesn't mean that the other reason for those entries specifically to be there isn't still there...

It's pretty clear they aren't mere dummy entries! And yet you felt the need to not bother asking why they were there before deleting! Good job I was able to spot this!

Not that there's actually a reason to remove that has been given! There's zero reason these _need_ to go, AFAICS.

**Comment by yakra** [comment]
The place to give examples would be in the manual, not in updates.csv.

**Comment by si404** [comment]
And when
1) the manual exists
2) I have a few hours free to write that page of it up (sorry I've been using the little free time I currently have to review road systems instead!)
it will move from it's temporary home to its final home.

But, even then, why would it need to go? What damage does it cause by being there?

**Comment by michihdeu** [comment]
sorry, I was happy about the fix and thought I could.... didn't expect.... sorry...

**Pull request closed without merging**
