### PR TITLE
add IAH subway and fix TMYellow

### PR DESCRIPTION
**Pull request by the-spui-ninja**

### CODE REVIEW

**Comment by si404** [comment]
You forgot the semicolon at the end of the line in usaair.csv

Don't worry - it's fixed, and those kinds of errors are ones I make regularly!

**Comment by michihdeu** [comment]
@the-spui-ninja don't you run data check?

**Comment by the-spui-ninja** [comment]
> @the-spui-ninja don't you run data check?

I don't know how... normally I'm pretty good about double and triple-checking that

**Comment by michihdeu** [comment]
Me too. However, I learned that the automated data check is better than me 😄

**Pull request merged**
