### PR TITLE
PATH and NYCS cleanup

### PR DESCRIPTION
**Pull request by Duke87ofST**

### CODE REVIEW

**Comment by Duke87ofST** [comment]
@jteresco

**Comment by jteresco** [comment]
Not sure why, but there are a ton of conflicts here.

**Comment by Duke87ofST** [comment]
> Not sure why, but there are a ton of conflicts here.

I think it's because the directory rail_data was renamed just "data" in the main branch and I hadn't synced my fork before I started working. If I try to sync it now, of course, it tells me I have a bunch of conflicts and I haven't found a sufficiently "for dummies" explanation on how to resolve such conflicts in order to actually be able to do it. 

If it'd be easier for me to undo my commits, sync my fork, and then redo my commits than for you to resolve the conflicts to merge this, let me know. 

Either way, I know I have to sync my fork before I do anything else.

**Comment by jteresco** [comment]
Now that I understand the problem I might be able to merge them in.  I'll give it a try.

**Comment by jteresco** [comment]
Might be good, I'll run a site update with the changes that ended up in the repository.

**Comment by Duke87ofST** [comment]
And as I suspected would happen, I was just able to sync my fork without it generating any conflicts. So this issue shouldn't come up again, at least so long as no one renames any more directories without me noticing.

**Pull request merged**
