### PR TITLE
TGV

### PR DESCRIPTION
**Pull request by si404**
this system is a mess (and Brittany is only outlined), but the bones are there.

### CODE REVIEW

**Comment by eeffaann** [comment]
Just a heads up, I'm done AVE from the French border into Madrid.I have Fig-Barcelona drafted on a branch.

**Comment by si404** [comment]
I used that draft to make the Spanish bit of the Paris - Barcelona route.

**Comment by eeffaann** [comment]
Yeah just checked all the points :) I suppose it wasn't so useless to have a stub draft PR out.

**Comment by michihdeu** [comment]
Nope, the stub is annoying. Please use the forum to arrange your work. Announce what region you are working on.

**Pull request merged**
