### PR TITLE
Add Chennai Metro

### PR DESCRIPTION
**Pull request by psvenk**
Add [Chennai Metro](https://en.wikipedia.org/wiki/Chennai_Metro). This includes all stations that are operational as of now, so I assume that it can be promoted to preview status soon. Let me know if I missed anything; it's my first time doing this. I tried to follow the [truncation rules](https://travelmapping.net/devel/manual/wayptlabels.php#truncate) based on the official English names of the stations.

### CODE REVIEW

**Comment by jteresco** [comment]
Has this been run through datacheck?

**Comment by psvenk** [comment]
I just now ran datacheck (with `./datacheck.sh --tmbasedir ~/src/github/TravelMapping --rail --use-python --numthreads 1 --nopull --noinstall`), and I got the `!!! DATA CHECK SUCCESSFUL !!!` message. (This was after re-designating `indcmrl` from devel to active to avoid a division-by-zero error due to there not being any active systems in `RailwayData`.)

I've rebased my branch on `master`; should this be ready to merge? I'm assuming that the protocol is to merge this as devel first and then open another pull request asking to promote it to preview after checking that everything's alright on the website.

**Comment by jteresco** [comment]
Thanks - I'm going to ask for a review from some of our railway data contributors to make sure things are looking good.

**Comment by si404** [comment]
I looked at the files - they seemed fine. Then I pulled it in and ran datacheck on it on my branch, and it was successful.

I'd say that it's looking good.

**Comment by psvenk** [comment]
Great; sounds good. Is there anything that I should do before opening a pull request to promote this to preview status?

**Pull request merged**
