### PR TITLE
Create Las Vegas Monorail

### PR DESCRIPTION
**Pull request by cl994**
Drafting Las Vegas Monorail and moving to preview systems

### CODE REVIEW

**Comment by michihdeu** [comment]
@cl994 you missed the _con.csv file. I guess that @jteresco fixed it locally only since the route is in RB now. Nonetheless, I'll add the _con.csv file now so that my data check runs through.

**Comment by jteresco** [comment]
No, I just didn't notice that the update failed!

**Comment by jteresco** [comment]
Running a new one now with a couple more things merged in.

**Comment by cl994** [comment]
Ugh, I knew I missed something. Thanks for fixing this.

**Pull request merged**
